//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightInfo
    {
        public FlightInfo()
        {
            this.Passengers = 0;
            this.Type = 0;
        }
    
        public int ID { get; set; }
        public string GUID { get; set; }
        public string LicenceTag { get; set; }
        public string Driver { get; set; }
        public string Number { get; set; }
        public string BusType { get; set; }
        public System.DateTime GoTime { get; set; }
        public int OverTime { get; set; }
        public decimal Price { get; set; }
        public int Passengers { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public System.DateTime OneDate { get; set; }
        public int PathInfoID { get; set; }
    
        public virtual PathInfo PathInfo { get; set; }
    }
}
