//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PathInfo
    {
        public PathInfo()
        {
            this.Distance = 0D;
            this.Time = 0;
            this.Status = 0;
        }
    
        public int ID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public double Distance { get; set; }
        public int Time { get; set; }
        public string Number { get; set; }
        public int Status { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Other { get; set; }
    }
}
