//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticketinfo
    {
        public Ticketinfo()
        {
            this.Money = 0m;
        }
    
        public int ID { get; set; }
        public string GUID { get; set; }
        public string FGUID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public decimal Money { get; set; }
        public string Number { get; set; }
        public int SeatNumber { get; set; }
        public System.DateTime Gotime { get; set; }
        public System.DateTime Arrtime { get; set; }
        public int Overtime { get; set; }
        public string Name { get; set; }
        public string IdCard { get; set; }
        public string Phone { get; set; }
        public System.DateTime BuyDate { get; set; }
        public System.DateTime OutDate { get; set; }
        public string BuyName { get; set; }
        public string BuyIdCard { get; set; }
        public string BuyPhone { get; set; }
        public int BuyType { get; set; }
        public string LicenceTag { get; set; }
        public string Driver { get; set; }
        public string BusType { get; set; }
        public int Passengers { get; set; }
        public int Status { get; set; }
    }
}
