//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Status = 0;
            this.Type = 0;
        }
    
        public int ID { get; set; }
        public string GUID { get; set; }
        public string Login { get; set; }
        public string Pwd { get; set; }
        public string UName { get; set; }
        public System.DateTime SignDate { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public string IdCard { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public string Other { get; set; }
    }
}
